server:
  port: 9001
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: consumer-server
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    sender:
      type: web
    base-url: http://127.0.0.1:9411/
  cloud:
    sentinel:
      transport:
        dashboard: http://localhost:10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 4
    lease-expiration-duration-in-seconds: 10
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.cloud.sleuth: DEBUG
    cn.cloud.xuli.mapper: debug
